{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "\n",
    "FOLDERS = {\n",
    "    \"preprocess\": \"./data/\",\n",
    "    \"train\": \"./model_output/\"\n",
    "}\n",
    "\n",
    "for folder in FOLDERS.values():\n",
    "    if not os.path.exists(folder):\n",
    "        os.makedirs(folder)\n",
    "\n",
    "PREPROCESS_CONFIGS = {\n",
    "    \"load\": {\n",
    "        \"raw_data\": FOLDERS[\"preprocess\"] + \"cs-training.csv\"\n",
    "    },\n",
    "    \"save\": {\n",
    "        \"preprocessed_data\": FOLDERS[\"preprocess\"] + \"preprocessed.csv\",\n",
    "        \"imputation\": FOLDERS[\"preprocess\"] + \"impute.p\"\n",
    "    },\n",
    "    \"impute\": False\n",
    "}\n",
    "\n",
    "TRAIN_CONFIGS = {\n",
    "    \"load\": {\n",
    "        \"preprocessed_data\": PREPROCESS_CONFIGS[\"save\"][\"preprocessed_data\"],\n",
    "    },\n",
    "    \"save\": {\n",
    "        \"model\": FOLDERS[\"train\"] + \"model.p\"\n",
    "    },\n",
    "    \"model_params\": {\n",
    "        'min_child_weight': list(range(1,10,2)),\n",
    "        'gamma':[i/10.0 for i in range(0,5)],\n",
    "        'subsample': [0.6, 0.8, 1.0],\n",
    "        'colsample_bytree':[i/10.0 for i in range(6,10)],\n",
    "        'max_depth':range(3,10,2),\n",
    "        'reg_alpha': [0, 0.001, 0.005, 0.01, 0.05, 0.1, 0.2],\n",
    "        'reg_lambda': [0, 0.001, 0.005, 0.01, 0.05, 0.2, 0.4, 0.6, 0.8, 1],\n",
    "        'learning_rate': [0.001, 0.002, 0.005, 0.006, 0.01, 0.02, 0.05, 0.1, 0.11, 0.12, 0.13, 0.14, 0.15, 0.2],\n",
    "        'n_estimators': [50, 100, 150, 200, 250, 300,350,400,450,500, 550, 600, 650, 700, 750],\n",
    "        \"booster\": [\"gbtree\", \"gblinear\", \"dart\"]\n",
    "        }\n",
    "}\n",
    "\n",
    "PRED_CONFIGS = {\n",
    "    \"load\": {\n",
    "        \"test_data\": FOLDERS[\"preprocess\"] + \"cs-test.csv\",\n",
    "        \"model\": TRAIN_CONFIGS[\"save\"][\"model\"],\n",
    "        \"imputation\": PREPROCESS_CONFIGS[\"save\"][\"imputation\"]\n",
    "    },\n",
    "    \"save\": {\n",
    "        \"predictions\": FOLDERS[\"train\"] + \"predictions.csv\"\n",
    "    },\n",
    "    \"impute\": PREPROCESS_CONFIGS[\"impute\"]\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# %load config.ipynb\n",
    "{\n",
    " \"cells\": [\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": 1,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"import os\\n\",\n",
    "    \"\\n\",\n",
    "    \"FOLDERS = {\\n\",\n",
    "    \"    \\\"preprocess\\\": \\\"./data/\\\",\\n\",\n",
    "    \"    \\\"train\\\": \\\"./model_output/\\\"\\n\",\n",
    "    \"}\\n\",\n",
    "    \"\\n\",\n",
    "    \"for folder in FOLDERS.values():\\n\",\n",
    "    \"    if not os.path.exists(folder):\\n\",\n",
    "    \"        os.makedirs(folder)\\n\",\n",
    "    \"\\n\",\n",
    "    \"PREPROCESS_CONFIGS = {\\n\",\n",
    "    \"    \\\"load\\\": {\\n\",\n",
    "    \"        \\\"raw_data\\\": FOLDERS[\\\"preprocess\\\"] + \\\"cs-training.csv\\\"\\n\",\n",
    "    \"    },\\n\",\n",
    "    \"    \\\"save\\\": {\\n\",\n",
    "    \"        \\\"preprocessed_data\\\": FOLDERS[\\\"preprocess\\\"] + \\\"preprocessed.csv\\\",\\n\",\n",
    "    \"        \\\"imputation\\\": FOLDERS[\\\"preprocess\\\"] + \\\"impute.p\\\"\\n\",\n",
    "    \"    },\\n\",\n",
    "    \"    \\\"impute\\\": False\\n\",\n",
    "    \"}\\n\",\n",
    "    \"\\n\",\n",
    "    \"TRAIN_CONFIGS = {\\n\",\n",
    "    \"    \\\"load\\\": {\\n\",\n",
    "    \"        \\\"preprocessed_data\\\": PREPROCESS_CONFIGS[\\\"save\\\"][\\\"preprocessed_data\\\"],\\n\",\n",
    "    \"    },\\n\",\n",
    "    \"    \\\"save\\\": {\\n\",\n",
    "    \"        \\\"model\\\": FOLDERS[\\\"train\\\"] + \\\"model.p\\\"\\n\",\n",
    "    \"    },\\n\",\n",
    "    \"    \\\"model_params\\\": {\\n\",\n",
    "    \"        'min_child_weight': list(range(1,10,2)),\\n\",\n",
    "    \"        'gamma':[i/10.0 for i in range(0,5)],\\n\",\n",
    "    \"        'subsample': [0.6, 0.8, 1.0],\\n\",\n",
    "    \"        'colsample_bytree':[i/10.0 for i in range(6,10)],\\n\",\n",
    "    \"        'max_depth':range(3,10,2),\\n\",\n",
    "    \"        'reg_alpha': [0, 0.001, 0.005, 0.01, 0.05, 0.1, 0.2],\\n\",\n",
    "    \"        'reg_lambda': [0, 0.001, 0.005, 0.01, 0.05, 0.2, 0.4, 0.6, 0.8, 1],\\n\",\n",
    "    \"        'learning_rate': [0.001, 0.002, 0.005, 0.006, 0.01, 0.02, 0.05, 0.1, 0.11, 0.12, 0.13, 0.14, 0.15, 0.2],\\n\",\n",
    "    \"        'n_estimators': [50, 100, 150, 200, 250, 300,350,400,450,500, 550, 600, 650, 700, 750],\\n\",\n",
    "    \"        \\\"booster\\\": [\\\"gbtree\\\", \\\"gblinear\\\", \\\"dart\\\"]\\n\",\n",
    "    \"        }\\n\",\n",
    "    \"}\\n\",\n",
    "    \"\\n\",\n",
    "    \"PRED_CONFIGS = {\\n\",\n",
    "    \"    \\\"load\\\": {\\n\",\n",
    "    \"        \\\"test_data\\\": FOLDERS[\\\"preprocess\\\"] + \\\"cs-test.csv\\\",\\n\",\n",
    "    \"        \\\"model\\\": TRAIN_CONFIGS[\\\"save\\\"][\\\"model\\\"],\\n\",\n",
    "    \"        \\\"imputation\\\": PREPROCESS_CONFIGS[\\\"save\\\"][\\\"imputation\\\"]\\n\",\n",
    "    \"    },\\n\",\n",
    "    \"    \\\"save\\\": {\\n\",\n",
    "    \"        \\\"predictions\\\": FOLDERS[\\\"train\\\"] + \\\"predictions.csv\\\"\\n\",\n",
    "    \"    },\\n\",\n",
    "    \"    \\\"impute\\\": PREPROCESS_CONFIGS[\\\"impute\\\"]\\n\",\n",
    "    \"}\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": []\n",
    "  }\n",
    " ],\n",
    " \"metadata\": {\n",
    "  \"kernelspec\": {\n",
    "   \"display_name\": \"Python 3\",\n",
    "   \"language\": \"python\",\n",
    "   \"name\": \"python3\"\n",
    "  },\n",
    "  \"language_info\": {\n",
    "   \"codemirror_mode\": {\n",
    "    \"name\": \"ipython\",\n",
    "    \"version\": 3\n",
    "   },\n",
    "   \"file_extension\": \".py\",\n",
    "   \"mimetype\": \"text/x-python\",\n",
    "   \"name\": \"python\",\n",
    "   \"nbconvert_exporter\": \"python\",\n",
    "   \"pygments_lexer\": \"ipython3\",\n",
    "   \"version\": \"3.8.3\"\n",
    "  }\n",
    " },\n",
    " \"nbformat\": 4,\n",
    " \"nbformat_minor\": 4\n",
    "}\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
